### PR TITLE
Swift 4

### LINKED ISSUE #22: Create swift4.0 branch
Currently RxSwift is at 4.0.0-alpha, but you cannot use RxCoreData against it because of the dependency to RxSwift ~>3.0.

### PR DESCRIPTION
**Pull request by AYastrebov**
- Updated to Swift 4 and RxSwift 4
- Fixes #22

### CODE REVIEW

**Comment by AYastrebov** [comment]
@bobgodwinx I've update the the swift version, thanks, missed that. Also updated the ```travis``` file. I think ```podfile.lock``` shouldn't be deleted, it should build now, but I can't access travis and check it

**Comment by bobgodwinx** [comment]
@AYastrebov I was referring also to the Podfile is in the `RxCoredata\Example`  you can remove this code below + and also delete the Podfile.lock from that same directory. Before running `pod install`
```Ruby
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.new_shell_script_build_phase.shell_script = "mkdir -p $PODS_CONFIGURATION_BUILD_DIR/#{target.name}"
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.0'
#            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
#        end
#    end
#end
``` 

I just tested it now. This should fix example project. The swift 4.0 is now set perfect 👍

**Comment by AYastrebov** [comment]
@bobgodwinx ok, got it. Updated the PR

**Comment by bobgodwinx** [comment]
@AYastrebov Working fine great job 🥇

**Pull request merged**
