### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by samscam**
This builds on the existing pull request #10 (also thereby issue #9) and updates the dependencies to the latest RxSwift as well as fixing the example app (there is now a swift 3 RxDataSources)

I've also bumped the version number in the podspec and updated the readme.

### CODE REVIEW

**Comment by scotteg** [comment]
Hi @samscam @sergdort @serluca Thanks for your work on this repo. I updated the project to recommended settings. Everything built and ran fine, so I merged @samscam's PR. However, now I'm unable to update CocoaPods trunk, because `lint` is failing:

```
=== CLEAN TARGET RxSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET RxSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
 -> RxCoreData (0.3.0-rc.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

Changing the build setting to use legacy does not resolve the issue, and running the converter generates several refactors:

screenshot 2016-10-19 07 14 19

Any suggestions? Thanks!

**Comment by serluca** [comment]
Hi @scotteg 

just do `echo "3.0" > .swift-version` and try again, then it should work

**Comment by scotteg** [comment]
@serluca Thanks for the suggestion, but that did not resolve the issue. Still getting the same error.

**Comment by serluca** [comment]
@scotteg what version of cocoapods are you using?

**Comment by scotteg** [comment]
@serluca I was running 1.0.0. So, I updated to 1.0.1 and tried again. Same error.

**Comment by chrisjrex** [comment]
How do things look for getting off of the '~> .rc' versions of RxSwift dependencies? All my other Rx pods now depend on the '~> 3.0.0' releases. So i can't run my side in swift 3 until.. i've tried every combination of the various pods. And looks like this is the only "sane" solution

So I hope dev is going well :)

**Comment by samscam** [comment]
@chrisjrex I submitted PR #16 last night which should sort that :)

**Comment by chrisjrex** [comment]
I was going to do one myself next week if no one had gotten around to it yet. So thank you :)

**Pull request merged**
